### ISSUE TITLE
Nice stolen bot idiot

### ISSUE THREAD

**Issue by Kyiro** [bjax25/Z-BOT#1]
You don't even know python aka the easiest programming lanugage
Go eat sand
You're fucking sad

**Comment by LenkyDev** [comment]
He didn't even hide the email and password

**Comment by bjax25** [comment]
stfu fag

**Comment by Kyiro** [comment]
LMFAO you can't remove github commits. Your bot's e-mail and password is still there idiot
btw i love your bot's username

**Comment by LenkyDev** [comment]
😂

**Comment by Kyiro** [comment]
so please
Go eat sand.

**Comment by xMistt** [comment]
> LMFAO you can't remove github commits. Your bot's e-mail and password is still there idiot
> btw i love your bot's username

You can but he doesn't know how to.

**Comment by Kyiro** [comment]
> > LMFAO you can't remove github commits. Your bot's e-mail and password is still there idiot
> > btw i love your bot's username
> 
> You can but he doesn't know how to.

Didn't know that

**Comment by wavy0** [comment]
how tf do you remove commits

**Comment by bjax25** [comment]
lmao
