### ISSUE TITLE
don't steal source code 

### ISSUE THREAD

**Issue by wavy0** [bjax25/Z-BOT#6]
1. why the fucking fuck are you stealing source code that is LICENSED.

2. its so obvious that you are stealing lmao

**Comment by bjax25** [comment]
yall are sad

**Comment by wavy0** [comment]
BRUH THIS IS STOLEN AND EVEN OLI(the creator of the original bot) KNOWS ABOUT THIS LOL

**Comment by bjax25** [comment]
fuck oli he banned me from partybot for no reason lmao

**Comment by wavy0** [comment]
that doesn't mean you can steal shit

**Comment by bjax25** [comment]
payback

**Comment by wavy0** [comment]
what did you get banned for in the first place lmao

**Comment by bjax25** [comment]
i was making a server and kicked him bc it wasn't finished yet

**Comment by wavy0** [comment]
lmao
